import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:sandiwapp/components/bulletList.dart';

class MemberPage extends StatefulWidget {
  const MemberPage({super.key});

  @override
  State<MemberPage> createState() => _MemberPageState();
}

class _MemberPageState extends State<MemberPage> {
  final ScrollController _scrollController = ScrollController();
  @override
  void dispose() {
    _scrollController.dispose(); // Always dispose the controller when done
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scrollbar(
      controller: _scrollController,
      interactive: true,
      thickness: 12,
      thumbVisibility: true,
      child: SingleChildScrollView(
        controller: _scrollController,
        child: Column(
          children: [
            Text("Founders", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Roberto Mata",
              "Ma. Theresa Payongayong",
              "Emmanuel Arca",
              "Dino Jose Baltao",
              "Wilhelmina Cruz",
              "Ferdinand Dela Cruz",
              "Medel dela Cruz",
              "Ma. Elena dela Cruz",
              "Michael dela Paz",
              "Jerome Diaz",
              "Matt Galang",
              "Dexter Pajarillo",
              "Julius Pronuevo",
              "Rudyard Roxas",
              "Maureen Salvador",
              "Michelle Iris Tan",
              "Leila Tecson Dominguez",
              "Liziel Tecson",
              "Joselito Tucit",
            ]),
            const SizedBox(height: 20),
            Text("Batch Unang Sibol",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Agnes Buencamino",
              "Rogelio Lunaria",
              "Sharon Rimando",
              "Leo Antonio San Pedro",
              "Mary Grace June San Pedro",
            ]),
            const SizedBox(height: 20),
            Text("Batch Alibangbang",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Adeva Andres",
              "Janelle dela Cruz",
              "Armina Evangelista",
              "Paul Fabian",
              "Joel Dimla Javier",
              "Vibeth Lazaro",
              "Victor Mendoza",
              "Geneson Marie Santos",
              "Gertrudes Sapitan",
            ]),
            const SizedBox(height: 20),
            Text("Batch Campupot",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Joanna Garcia",
              "Myla Lee-Tolentino",
            ]),
            const SizedBox(height: 20),
            Text("Batch Narra", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Archieval Garcia",
            ]),
            const SizedBox(height: 20),
            Text("Batch Piramida",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Michelle Cruz",
              "Jennifer Fabian",
              "Hanziel Gelogo",
              "Melisa Mercado",
              "Johnalyn Sevilla",
            ]),
            const SizedBox(height: 20),
            Text("Batch Ulan", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Victor Angagan Jr.",
              "Gina Camposano",
            ]),
            const SizedBox(height: 20),
            Text("Batch Bato", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Crispin Cruz",
              "Ma. Antonio Cruz",
              "Johanna Enriquez",
            ]),
            const SizedBox(height: 20),
            Text("Batch Bigkis",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Manuel Esguerra",
              "Odyssey Paris",
            ]),
            const SizedBox(height: 20),
            Text("Batch Araw", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Khristian Kikuchi",
            ]),
            const SizedBox(height: 20),
            Text("Batch Luwad", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Dionella Castillo",
              "Arianne Cruz",
              "Marie Fe Geron",
              "Maricar Santos",
            ]),
            const SizedBox(height: 20),
            Text("Batch Solo", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Flor Katrina Gulla",
            ]),
            const SizedBox(height: 20),
            Text("Batch Makahiya",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Maricris Cruz",
            ]),
            const SizedBox(height: 20),
            Text("Batch Bukang-Liwayway",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Ana Carmina Dionicio",
            ]),
            const SizedBox(height: 20),
            Text("Batch Laya", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Elmer Polintan",
            ]),
            const SizedBox(height: 20),
            Text("Batch Kalawakan",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Lyonelle Laurice Bernardino",
              "Joel Hilario",
              "Reggie Llopis",
              "Paulo Christian Romero",
            ]),
            const SizedBox(height: 20),
            Text("Batch Silang",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Anna Krislyn Angosino",
            ]),
            const SizedBox(height: 20),
            Text("Batch Sandalan",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Romina Camua",
            ]),
            const SizedBox(height: 20),
            Text("Batch Binhi", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Julie Ann Angeles",
              "Joyce Hernandez",
            ]),
            const SizedBox(height: 20),
            Text("Batch Kanlungan",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Charles Edward Aguinaldo",
              "Mark Stanley Cieto",
              "Dan Angelo Guardian",
              "Julius Lagco",
            ]),
            const SizedBox(height: 20),
            Text("Batch Paninindigan",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Amadelle Rose Suñer",
            ]),
            const SizedBox(height: 20),
            Text("Batch Astig", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Fermina Joy Delos Santos",
              "Jose William Enriquez",
              "Maria Arcelli Lazaro",
              "Angelo Hernan Melencio",
              "Glaiza Suzuki",
            ]),
            const SizedBox(height: 20),
            Text("Batch Busilak",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Mark Lexter de Lara",
              "Laarni Reyes",
            ]),
            const SizedBox(height: 20),
            Text("Batch Bahaghari",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Christina Cruz",
              "Jayvee Cruz",
              "Mary Anne Cruz",
              "Analyn Esteban",
              "Kristine Soleill Magpayo",
            ]),
            const SizedBox(height: 20),
            Text("Batch Dapit-Hapon",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Maria Niña Amor Castro",
              "Rose Ann de Lara",
              "Apple Espino",
              "Danielle Manalaysay",
              "Gladys Joyce Mercado",
              "Ma. Daniella Helena Nieva",
            ]),
            const SizedBox(height: 20),
            Text("Batch Kaflo Fedew",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Xehoshua Paolo Katindig",
              "Frances Michelle Nubla",
            ]),
            const SizedBox(height: 20),
            Text("Batch Tanikala",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Abigail Castillo",
              "Jessica Marie Esguerra",
            ]),
            const SizedBox(height: 20),
            Text("Batch Tampipi",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Ma. Ruiza Rivera",
            ]),
            const SizedBox(height: 20),
            Text("Batch Balintataw",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Alastair Benigno Fabros",
              "Leni Gene Gonzalez",
              "Miriam Gutierrez",
            ]),
            const SizedBox(height: 20),
            Text("Batch Salinlahi",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Kevin Moses Bautista",
              "Richard Estrella",
              "Marvil Villania",
            ]),
            const SizedBox(height: 20),
            Text("Batch Tim-Tim",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Gellie Grace Bandojo",
              "Camille Gonzales",
              "Daryll Malabanan",
              "Romil Tuando",
            ]),
            const SizedBox(height: 20),
            Text("Batch Pilak", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Jonathan Avellanosa",
              "Ma. Veronica Sapasap",
            ]),
            const SizedBox(height: 20),
            Text("Batch Ningas",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Jahzeel Dela Rosa",
              "Kevin Ross Sales",
            ]),
            const SizedBox(height: 20),
            Text("Batch Lulan", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Jun Mark delos Reyes",
              "Carla San Diego",
              "Melody Santiago",
              "Cindy Villavicencio",
            ]),
            const SizedBox(height: 20),
            Text("Batch Kalasag",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Melvin Ilang-ilang",
            ]),
            const SizedBox(height: 20),
            Text("Batch Baitang",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Ana Marie Robles",
            ]),
            const SizedBox(height: 20),
            Text("Batch Uhay", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Ma. Queenie Fabon",
            ]),
            const SizedBox(height: 20),
            Text("Batch Uhay", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Ralson Hernandez",
              "Cathlyn Jasareno",
            ]),
            const SizedBox(height: 20),
            Text("Batch Marubdob",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Mary Angeline Marilao",
              "Axel Rozz Villanueva",
            ]),
            const SizedBox(height: 20),
            Text("Batch Bangon",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "June Lander Alastoy",
              "Kentucky Potrido",
            ]),
            const SizedBox(height: 20),
            Text("Batch Ligaya",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Eloisa Roxanne Estrellado",
              "Maridel Fidelino",
            ]),
            const SizedBox(height: 20),
            Text("Batch Singkaban",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Marianne Clarice Gutierrez",
              "Paula Camille Ingalla",
              "Dana Jean Navarro",
              "Rhomalet Keeshiah Ong",
            ]),
            const SizedBox(height: 20),
            Text("Batch Puso", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Raphael Ernesto Tuazon",
            ]),
            const SizedBox(height: 20),
            Text("Batch Tadhana",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Johnwin Enrico Aguilar",
              "John Denielle Hernandez",
              "Jan Erwin dela Cruz Reyes",
              "Denielle Unay",
            ]),
            const SizedBox(height: 20),
            Text("Batch Alab", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Jacqueline Concepcion",
              "Ryne Francis Aboga",
              "Ma. Eleonor Louise Locasia",
              "Jessa Abejo",
              "Elbert Valenzuela",
              "Marivic Mercado",
              "Kim Lai",
            ]),
            const SizedBox(height: 20),
            Text("Batch Marikit",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Abigael Cesar",
            ]),
            const SizedBox(height: 20),
            Text("Batch Batingaw",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Princess Collin Borromeo",
              "Marie Eugenie De Guzman",
              "Arvin Rafael SG Lizardo",
              "Efren Mercado Jr.",
              "Honey Grace Pineda",
              "Luis Angelo Santos",
              "Allan Philip Valenzuela",
            ]),
            const SizedBox(height: 20),
            Text("Batch Siklab-diwa",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "John Paul Alfiller",
              "Aldrin Dale Garces",
            ]),
            const SizedBox(height: 20),
            Text("Batch Indayog",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Camille Dacillo",
              "Carmina Dela Cruz",
            ]),
            const SizedBox(height: 20),
            Text("Batch Matatag",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Rowie Joy Bucks",
              "Vella Dela Cruz",
            ]),
            const SizedBox(height: 20),
            Text("Batch Sinag", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Denzel Casas",
              "Maria Denise Gamboa",
              "John Armon Ortega",
              "Joanna Marie Timario",
              "Kristel Velasquez",
            ]),
            const SizedBox(height: 20),
            Text("Batch Lakambini",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Julia Beatriz Iglesias",
              "Arlette Clare Marco",
              "Celestine Joy Membrebe",
              "Marleth Temporal",
              "Nicolle Villa",
            ]),
            const SizedBox(height: 20),
            Text("Batch Dagitab",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Israel Joshua Divinagracia",
              "Francis Cholo Manglicmot",
              "Jedidiah Sarmiento",
            ]),
            const SizedBox(height: 20),
            Text("Batch Talulot",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Renée Anne Mendoza",
            ]),
            const SizedBox(height: 20),
            Text("Batch Virtuoso",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Kirby Valerio",
            ]),
            const SizedBox(height: 20),
            Text("Batch Kidlat",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Keith Jalen Dela Cruz",
              "Harlene May Viesca",
            ]),
            const SizedBox(height: 20),
            Text("Batch Sansinukob",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Albert Dominick Crisostomo",
            ]),
            const SizedBox(height: 20),
            Text("Batch Marahuyo",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Kyle Edmark De Guzman",
            ]),
            const SizedBox(height: 20),
            Text("Batch Kinaadman",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Neil Given Dimagiba",
              "Clara Nina Manlutac",
              "Mhel Angelo Policarpio",
            ]),
            const SizedBox(height: 20),
            Text("Batch Ilog", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Maiah Cheng",
              "James Salera",
              "Aleksandre San Gabriel",
            ]),
            const SizedBox(height: 20),
            Text("Batch Panday-Pilak",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Enrico Miguel Astrologo",
              "Carl Bautista",
              "Marnnie Lee Bautista",
              "Arthur Frederick Catanghal",
              "Jon Vincent Carl Cruz",
              "Elaine De Guzman",
              "Maria Nereeza Francia",
              "Ric Sebastiane Joson",
              "Jaspher Pandaraoan",
              "Angel Keith Rejano",
              "Jamilyn Santos",
              "Martin Raphael Torres",
              "Dana Mae Yarte",
            ]),
            const SizedBox(height: 20),
            Text("Batch Sinagtala",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Ruel Simbulan",
              "Kobe Bernardo",
            ]),
            const SizedBox(height: 20),
            Text("Batch Hiraya Manawari",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Jan Carlo Basilio",
              "Lysa Mikaella Castillo",
              "Delmyr Angelyka Celestino",
              "Svetlana Dela Cruz",
              "Ranzmae German",
              "Erica Bianca Guillermo",
              "Paulynne Lorenzo",
              "Aleeza Merce Nolido",
              "Paul Angelo Solaina",
            ]),
            const SizedBox(height: 20),
            Text("Batch Banaag",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Patrick Josh Atayde",
              "John Henry Barcelona",
              "Mikko Bartolome",
              "Jazel Anne Bustrillo",
              "Adrian Cueto",
              "Smarie Shane Dela Rosa",
              "Katherine Denise Gonzales",
              "Irish Gwyneth Habig",
              "Luigy Jose",
              "Dana Joi Maningas",
              "Francheska Shine Arlei Nuica",
              "Lyka Mae Reyes",
              "Ma. Jazmine Rosellos",
              "Nicole Ann Vergara",
              "Tonie Lee Villanueva",
            ]),
            const SizedBox(height: 20),
            Text("Batch Tahanan",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Alliah Ledesma",
              "Raven Alexia Viñas",
              "Marian Casimiro",
              "Micaella Dayrit",
              "Mikaela Isabel Peña",
              "Reign Cyril De Vera",
              "Raven Dessery Joaquin",
              "Zyrelle Castellano",
              "Jenelle Marie San Miguel",
              "Franchesca Leila Salvador",
              "Kyle Andrew Dammay",
              "Romar Villena",
              "Frederick Emmanuel Estares",
              "Charmaine Libunao",
              "Aira Angela Domingo",
              "Reamonn Lois Domingo",
              "Mary Edlynn Atayde",
            ]),
            const SizedBox(height: 20),
            Text("Batch Alpas", style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Iraj Danielle Leopold Tumada",
              "Alyssa Nicole Canosa",
              "Alliyah Mae Suansing",
              "Almar Kyle Castro",
              "Jerome Lentijas",
              "John Cedric Llantos",
              "Kathleen Kate Leoncio",
              "Neil Andrew Tallayo",
              "Saulo Paul Bautista",
            ]),
            const SizedBox(height: 20),
            Text("Batch Tindig",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Vince Andrey Cabudoc",
              "Ella Sydney Catarroja",
              "Dave Elcarte",
              "Ma. Claudette Ocampo",
              "Janriel Pascual",
              "Ianna Nicole Sabijon",
            ]),
            const SizedBox(height: 20),
            Text("Batch Obra Maestra",
                style: GoogleFonts.patrickHandSc(fontSize: 24)),
            BulletList([
              "Jimwell Lumaquez",
              "Anthony Tayamora",
              "Aubrey Mariano",
              "Cesca Bondoc",
              "Earl Angelo Dela Cruz",
              "Jaicel Franzin Cruz",
              "Joanna Dayag",
              "Maverick Caballero",
              "Michelle Alarios",
              "Mary Joy Santos",
              "Daniela Jenine Orit",
              "Nicole Marie Mendoza",
              "Rafael Suñga",
            ]),
          ],
        ),
      ),
    );
  }
}
